name: Format Python code

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./FastAPI
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0 # 履歴全体をフェッチすることで、pushする際に必要な情報を保持します
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' # お使いのPythonのバージョンに合わせてください
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root
    - name: Run Black
      run: poetry run black .
    - name: Run isort
      run: poetry run isort .
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply black and isort formatting
        branch: ${{ github.head_ref }}
        file_pattern: . # 変更されたファイルを指定します。'.'は全ファイルを意味します。
