name: Format Python

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./FastAPI
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root

    - name: Run Black
      run: poetry run black .
    - name: Run isort
      run: poetry run isort .
